### ISSUE TITLE
Does not seem to be picking up on learn.microsoft.com

### ISSUE THREAD

**Issue by lukemurraynz** [nikneem/skilling-champion#1]
When attempting to add a Skilling Champion ID to the following link:

- https://learn.microsoft.com/rest/api/

It does not attempt to fix the issue.

Various supported URLs can be found here: https://github.com/mjisaak/skilling-champion-extension#suitable-sites

**Comment by nikneem** [comment]
Should be fixed by 1.0.5 (deployed moments ago), can you confirm?
